#!/bin/sh
echo "*** starting sdm230device ***"
## export PYTHONMALLOCSTATS=1
# Use device IDs to identiy the serial port so it is stable, sometimes the kernel will remap the tty if it detects
# a problem with the usb hardware. It cant remap the USB ids
exec 2>&1
exec /data/sdm230device/main.py -s /dev/serial/by-id/usb-WCH.CN_USB_Quad_Serial_BCD97DABCD-if02 -r 9600